export { openDatabase, type OpenDatabase } from './client.js';
export { checkIntegrity, type IntegrityCheck } from './health.js';
export { migrateDatabase } from './migrate.js';
export { appMetadata, coreSchema, workspaceSettings } from './schema/core.js';
export { products } from './schema/products.js';
export { productFactLineages, productFacts } from './schema/product-facts.js';
export { skuValues, skus, specificationDimensions, specificationValues } from './schema/skus.js';
export { DrizzleProductRepository } from './repositories/product-repository.js';
export { DrizzleProductFactRepository } from './repositories/product-fact-repository.js';
export { DrizzleSkuMatrixRepository } from './repositories/sku-matrix-repository.js';
